---
title: "social capital index"
author: "Wesley_Tao"
date: "2018.3.29"
output: html_document
---

Task 1: Please provide a visualization of this data in a map format that describes the changing social capital by county from years 1997 to 2014. 
Task 2: Provide analyses on the change of social capital over time by the statistical method of your choice

```{r message=FALSE}
library("xlsx") # load the data
# import the packages we are going to use
library("choroplethr")
library("choroplethrMaps")

table_1997<-read.xlsx("../data/social capital 1997-2014.xlsx", 1)
table_2005<-read.xlsx("../data/social capital 1997-2014.xlsx", 2)
table_2009<-read.xlsx("../data/social capital 1997-2014.xlsx", 3)
table_2014<-read.xlsx("../data/social capital 1997-2014.xlsx", 4)
```

```{r}
head(table_2014)# take a look at the head
```

```{r message=FALSE,warning=FALSE}

# plotmap function encapsulate everything
plotmap<-function(df,year){
  tempdata<-df[,c(1,3)]
  names(tempdata)<-c("region","value")
  county_choropleth(tempdata,
                  title = paste(year, "Social Capital index by county"),
                  legend="index")
  }
```
```{r warning=FALSE}
# map for 1997
plotmap(table_1997,"1997")

```
```{r warning=FALSE}
plotmap(table_2005,"2005") # map for 2006
```


```{r warning=FALSE}
plotmap(table_2009,"2009") # map for 2009
```

```{r warning=FALSE}
plotmap(table_2014,"2014") # map for 2014
```













